// Code generated by protoc-gen-go. DO NOT EDIT.
// source: urlShorter.proto

package urlShorter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShortRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortRequest) Reset()         { *m = ShortRequest{} }
func (m *ShortRequest) String() string { return proto.CompactTextString(m) }
func (*ShortRequest) ProtoMessage()    {}
func (*ShortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_urlShorter_e1d1ea73c8b67ea5, []int{0}
}
func (m *ShortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortRequest.Unmarshal(m, b)
}
func (m *ShortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortRequest.Marshal(b, m, deterministic)
}
func (dst *ShortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortRequest.Merge(dst, src)
}
func (m *ShortRequest) XXX_Size() int {
	return xxx_messageInfo_ShortRequest.Size(m)
}
func (m *ShortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShortRequest proto.InternalMessageInfo

func (m *ShortRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ShortResponse struct {
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortResponse) Reset()         { *m = ShortResponse{} }
func (m *ShortResponse) String() string { return proto.CompactTextString(m) }
func (*ShortResponse) ProtoMessage()    {}
func (*ShortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_urlShorter_e1d1ea73c8b67ea5, []int{1}
}
func (m *ShortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortResponse.Unmarshal(m, b)
}
func (m *ShortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortResponse.Marshal(b, m, deterministic)
}
func (dst *ShortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortResponse.Merge(dst, src)
}
func (m *ShortResponse) XXX_Size() int {
	return xxx_messageInfo_ShortResponse.Size(m)
}
func (m *ShortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShortResponse proto.InternalMessageInfo

func (m *ShortResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type FullRequest struct {
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullRequest) Reset()         { *m = FullRequest{} }
func (m *FullRequest) String() string { return proto.CompactTextString(m) }
func (*FullRequest) ProtoMessage()    {}
func (*FullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_urlShorter_e1d1ea73c8b67ea5, []int{2}
}
func (m *FullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullRequest.Unmarshal(m, b)
}
func (m *FullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullRequest.Marshal(b, m, deterministic)
}
func (dst *FullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullRequest.Merge(dst, src)
}
func (m *FullRequest) XXX_Size() int {
	return xxx_messageInfo_FullRequest.Size(m)
}
func (m *FullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FullRequest proto.InternalMessageInfo

func (m *FullRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type FullResponse struct {
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullResponse) Reset()         { *m = FullResponse{} }
func (m *FullResponse) String() string { return proto.CompactTextString(m) }
func (*FullResponse) ProtoMessage()    {}
func (*FullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_urlShorter_e1d1ea73c8b67ea5, []int{3}
}
func (m *FullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullResponse.Unmarshal(m, b)
}
func (m *FullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullResponse.Marshal(b, m, deterministic)
}
func (dst *FullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullResponse.Merge(dst, src)
}
func (m *FullResponse) XXX_Size() int {
	return xxx_messageInfo_FullResponse.Size(m)
}
func (m *FullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FullResponse proto.InternalMessageInfo

func (m *FullResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*ShortRequest)(nil), "ShortRequest")
	proto.RegisterType((*ShortResponse)(nil), "ShortResponse")
	proto.RegisterType((*FullRequest)(nil), "FullRequest")
	proto.RegisterType((*FullResponse)(nil), "FullResponse")
}

func init() { proto.RegisterFile("urlShorter.proto", fileDescriptor_urlShorter_e1d1ea73c8b67ea5) }

var fileDescriptor_urlShorter_e1d1ea73c8b67ea5 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0xca, 0x09,
	0xce, 0xc8, 0x2f, 0x2a, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe0, 0xe2,
	0x01, 0x0b, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0x97, 0x16, 0xe5,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a, 0x8a, 0x5c, 0xbc, 0x50, 0x15, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x30, 0x25, 0x4c, 0x08, 0x25, 0xf2, 0x5c, 0xdc, 0x6e, 0xa5, 0x39,
	0x39, 0x68, 0x66, 0x30, 0x23, 0x14, 0x28, 0x70, 0xf1, 0x40, 0x14, 0xa0, 0x1a, 0xc1, 0x02, 0x57,
	0x61, 0x94, 0xcc, 0xc5, 0x85, 0x70, 0x9b, 0x90, 0x36, 0x17, 0x87, 0x7b, 0x6a, 0x09, 0x98, 0x27,
	0xc4, 0xab, 0x87, 0xec, 0x40, 0x29, 0x3e, 0x3d, 0x14, 0xd7, 0x28, 0x31, 0x08, 0x69, 0x70, 0xb1,
	0xbb, 0xa7, 0x96, 0x80, 0xcc, 0x17, 0xe2, 0xd1, 0x43, 0x72, 0x87, 0x14, 0xaf, 0x1e, 0xb2, 0xa5,
	0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x3f, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36, 0x7a, 0xaf,
	0xac, 0x07, 0x01, 0x00, 0x00,
}
